In [1]:
import pandas as pd

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

In [3]:
df = pd.DataFrame(data = d)
df.head()

     sales          city    size
0   100000         Tampa   Small
1   222000         Tampa  Medium
2  1000000       Orlando   Large
3   522000  Jacksonville   Large
4   111111         Miami   Small

In [5]:
df['city'].nunique()

4

gonna use one hot encoding on city

In [6]:
df['city'].value_counts()

city
Orlando         5
Miami           3
Tampa           2
Jacksonville    2
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(handle_unknown= 'ignore',sparse_output= False).set_output(transform='pandas')

#handle_unknown =if i get a new column in testing which i didn't work on training , don't give me an error
#sparse_output = sparse is way of storing large data where it stores only the null values (good for large data)
#but we have small data so i wouldn't sparse my data
#with set_output i would get transformed data as pandas dataframe, without it i would get a numpy array

In [ ]:
ohetransform = ohe.fit_transform(df[['city']])   #always two dimensional : df[['city']]

In [12]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [ ]:
df = pd.concat([df,ohetransform],axis=1).drop(columns = ['city'])

In [14]:
df.head()

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0